language: go

go:
  - 1.7
  - 1.8
  - tip

#before_install:
#  - go get github.com/axw/gocov/gocov
#  - go get github.com/mattn/goveralls
#  - go get golang.org/x/tools/cmd/cover

install:
    - go get github.com/stretchr/testify
    - go get github.com/spf13/cobra
    - go get github.com/shivakar/xxhash
    - ./create_hardlinks.sh
#- cd testdata && rm b_hardlink.txt && ln b.txt b_hardlink.txt && cd ..
#- cd testdata/dir2/dir3 && rm d_hardlink.txt && ln ../../d.txt d_hardlink.txt && cd ../../..

#script:
#  - $HOME/gopath/bin/goveralls -service=travis-ci
