language: go

go:
  - 1.10.3

install:
  - go get github.com/stretchr/testify
  - go get github.com/spf13/cobra
  - go get github.com/shivakar/xxhash
  - ./create_hardlinks.sh

script:
  - go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
