language: go

go:
  - 1.7
  - 1.8
  - tip

#before_install:
#  - go get github.com/axw/gocov/gocov
#  - go get github.com/mattn/goveralls
#  - go get golang.org/x/tools/cmd/cover

install:
    - go get github.com/stretchr/testify
    - go get github.com/spf13/cobra
    - go get github.com/shivakar/xxhash
    - cd testdata && rm b_hardlink.txt && ln b.txt b_hardlink.txt && cd ..
    - rm testdata/dir2/dir3/d_hardlink.txt && ln testdata/d.txt testdata/dir2/dir3/d_hardlink.txt

#script:
#  - $HOME/gopath/bin/goveralls -service=travis-ci
